# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- azure_pipelines
- pr
- develop
- staging
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  devFolder: '/srv/fpe-dev.finsemble.com/htdocs/ecosystem/additions/components/fpe-bloomberg'
  devDocs: '/srv/fpe-dev.finsemble.com/htdocs/fpe-bloomberg'
  stagingDocs: '/srv/fpe-staging.finsemble.com/htdocs/fpe-bloomberg'
  masterDocs: '/srv/fpe.finsemble.com/htdocs/fpe-bloomberg'
  stagingFolder: '/srv/fpe-staging.finsemble.com/htdocs/ecosystem/additions/components/fpe-bloomberg'
  masterFolder: '/srv/fpe.finsemble.com/htdocs/ecosystem/additions/components/fpe-bloomberg'

steps:
- bash: |
    choco install docfx -y
    docfx BloombergBridge/docfx_project/docfx.json
    mkdir fpe-bloomberg
    cp -r BloombergBridge/docfx_project/fpe-bloomberg/* fpe-bloomberg/
    ls fpe-bloomberg
  displayName: "docfx build"
- task: SSH@0
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  inputs:
    sshEndpoint: 'Azure Connect7'
    runOptions: 'inline'
    inline: |
      #!/bin/bash
      # Reset permissions before Azure DevOps deployment
      echo “Reset permissions before Azure DevOps deployment”
      sudo chown -R azure:azure $(devDocs)
- task: CopyFilesOverSSH@0
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  inputs:
    sshEndpoint: 'Azure Connect7'
    sourceFolder: 'fpe-bloomberg'
    targetFolder: '$(devDocs)'
    overwrite: true
    failOnEmptySource: true

- task: SSH@0
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  inputs:
    sshEndpoint: 'Azure Connect7'
    runOptions: 'inline'
    inline: |
      #!/bin/bash
      # Reset permissions after Azure DevOps deployment
      echo “Reset permissions after Azure DevOps deployment”
      sudo chown -R www-data:www-data $(devDocs)

- task: SSH@0
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/staging'))
  inputs:
    sshEndpoint: 'Azure Connect7'
    runOptions: 'inline'
    inline: |
      #!/bin/bash
      # Reset permissions before Azure DevOps deployment
      echo “Reset permissions before Azure DevOps deployment”
      sudo chown -R azure:azure $(stagingDocs)
- task: CopyFilesOverSSH@0
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/staging'))
  inputs:
    sshEndpoint: 'Azure Connect7'
    sourceFolder: 'fpe-bloomberg'
    targetFolder: '$(stagingDocs)'
    overwrite: true
    failOnEmptySource: true

- task: SSH@0
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/staging'))
  inputs:
    sshEndpoint: 'Azure Connect7'
    runOptions: 'inline'
    inline: |
      #!/bin/bash
      # Reset permissions after Azure DevOps deployment
      echo “Reset permissions after Azure DevOps deployment”
      sudo chown -R www-data:www-data $(stagingDocs)


- task: SSH@0
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    sshEndpoint: 'Azure Connect7'
    runOptions: 'inline'
    inline: |
      #!/bin/bash
      # Reset permissions before Azure DevOps deployment
      echo “Reset permissions before Azure DevOps deployment”
      sudo chown -R azure:azure $(masterDocs)
- task: CopyFilesOverSSH@0
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    sshEndpoint: 'Azure Connect7'
    sourceFolder: 'fpe-bloomberg'
    targetFolder: '$(masterDocs)'
    overwrite: true
    failOnEmptySource: true

- task: SSH@0
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    sshEndpoint: 'Azure Connect7'
    runOptions: 'inline'
    inline: |
      #!/bin/bash
      # Reset permissions after Azure DevOps deployment
      echo “Reset permissions after Azure DevOps deployment”
      sudo chown -R www-data:www-data $(masterDocs)